// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	Title  *string `json:"title"`
	Author *User   `json:"author"`
}

type PostInput struct {
	Title  *string    `json:"title"`
	Author *UserInput `json:"author"`
}

type User struct {
	ID    string  `json:"id"`
	Name  *string `json:"name"`
	Posts []*Post `json:"posts"`
}

type UserInput struct {
	Name string `json:"name"`
}

type Workspace struct {
	WorkspaceID int `json:"workspaceID"`
	UserID      int `json:"userID"`
}

type CreateEdgeSitesWorkspace struct {
	WorkspaceID int `json:"workspaceID"`
	UserID      int `json:"userID"`
}
