// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	Title  *string `json:"title"`
	Author *User   `json:"author"`
}

type User struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
}
